permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Ecsys
  email: tbd@tbd.tbd
  link: http://ecsys.github.io
  github: http://github.com/ecsys

# 站点信息
title: ECSYS
description: TBD
url: http://ecsys.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/img/avatar.jpg
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
#ga:
  #id: UA-54767140-1
  #url: yansu.org

# disqus 设置
disqus:
  shortname: ecsys 
